apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-service
  labels:
    app: simple-nodejs-app
spec:
  type: NodePort
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
